### ISSUE TITLE
Create an easy way to delete the customer ID for Stripe in the customer profiles. 

### ISSUE THREAD

**Issue by slash1andy** [woothemes/woocommerce-gateway-stripe#11]
#### What I expected

Would love an easy way for someone to delete the Stripe customer profile that is created by Stripe and saved in WooCommerce. 

#### What happened instead

This has to be done in the database, which can be daunting to many of our users. The typical use case is when someone uses their own user for testing purposes, which has a test mode user created in Stripe. When they move the gateway to live, they need to delete the Stripe customer associated with the WordPress user in order to be able to test the live mode, but it's almost easier for them to just delete the entire WordPress user than find the row in `wp_usermeta`.

What I would love to see is the row showing the Stripe customer info in the users' page in WordPress, but obviously I defer to y'all :)

CC: @gedex

**Comment by mikejolley** [comment]
No longer needed @gedex - in the new version, if the customer ID is invalid (sandbox), it will be removed during process_payment and a new one will be created and assigned to user meta.
