### ISSUE TITLE
Compatibility w/Pre Orders 

### ISSUE THREAD

**Issue by WillBrubaker** [woothemes/woocommerce-gateway-stripe#20]
#### What I expected
For my [WooCommerce Pre-Orders](https://www.woothemes.com/products/woocommerce-pre-orders/) to be in a pre-order status when paying with stripe - see ticket: #430712-zd-woothemes

#### What happened instead
With the combination of WooCommerce ~~2.5.5~~ (edited, version doesn't seem to matter), Subscriptions (edit - added subscriptions to the mix), Pre-Orders 1.4.5 and Stripe >= 3.0.0 pre-order items have their payment collected immediately

#### Steps to reproduce the issue
1. WooCommerce ~~2.5.5 (or below I presume)~~ is installed and active
2. Pre-orders installed & active 
3. Stripe at 3.0 to 3.0.2
4. A product is configured as a pre-order product available for some time in the future and "when to charge" is set for "Upon Release"
5. Pre-order that product and complete the checkout process.
6. See that the order is in a processing status and the pre-order associated with that order is not active.

~~updating to WooCommerce 2.6~~ installing/activating Subscriptions will solve this as will downgrading to Stripe 2.6.12

@mdmoore @gedex 

-------------------

- [x] Issue assigned to next milestone.
- [x] Issue assigned a priority (will be assessed by maintainers).

**Comment by WillBrubaker** [comment]
@gedex update on the above.

This actually seems to happen if WooCommerce Subscriptions is **NOT** active and Stripe is at v3.0 or above. Installing/activating Subscriptions will cause pre-orders to work as expected but without it, pre-orders does not work as expected so I'm guessing there's some magic in Subscriptions that is missing in Stripe 3.0+

**Comment by gedex** [comment]
Thanks for the additional info @WillBrubaker . I found the culprit to be here https://github.com/woothemes/woocommerce-gateway-stripe/blob/master/woocommerce-gateway-stripe.php#L278-L280 where addons only loaded when subscription is active.

**Comment by gedex** [comment]
@WillBrubaker could you try `issues/20/fix-pre-order` branch and verify whether it fixes the issue?

**Comment by WillBrubaker** [comment]
@gedex I'm still having the same problem

**Comment by gedex** [comment]
@WillBrubaker Since this has been merged and one commit is left post merge, could you try pull from `master` ?

**Comment by WillBrubaker** [comment]
@gedex That seems to have it sorted :)
