### ISSUE TITLE
Customizable Credit Card Icons

### ISSUE THREAD

**Issue by BFTrick** [woothemes/woocommerce-gateway-stripe#25]
Users should be able to customize the credit card icons they accept. 

We've simplified it to if you accept USD you should display all CC icons but that's an oversimplification. There are Canadian accounts which accept USD and they can only accept: Visa, Mastercard, & Amex.

``` php
$icon  = '<img src="' . WC_HTTPS::force_https_url( WC()->plugin_url() . '/assets/images/icons/credit-cards/visa' . $ext ) . '" alt="Visa" width="32" ' . $style . ' />';
$icon .= '<img src="' . WC_HTTPS::force_https_url( WC()->plugin_url() . '/assets/images/icons/credit-cards/mastercard' . $ext ) . '" alt="Mastercard" width="32" ' . $style . ' />';
$icon .= '<img src="' . WC_HTTPS::force_https_url( WC()->plugin_url() . '/assets/images/icons/credit-cards/amex' . $ext ) . '" alt="Amex" width="32" ' . $style . ' />';
if ( 'USD' === get_woocommerce_currency() ) {
	$icon .= '<img src="' . WC_HTTPS::force_https_url( WC()->plugin_url() . '/assets/images/icons/credit-cards/discover' . $ext ) . '" alt="Discover" width="32" ' . $style . ' />';
	$icon .= '<img src="' . WC_HTTPS::force_https_url( WC()->plugin_url() . '/assets/images/icons/credit-cards/jcb' . $ext ) . '" alt="JCB" width="32" ' . $style . ' />';
	$icon .= '<img src="' . WC_HTTPS::force_https_url( WC()->plugin_url() . '/assets/images/icons/credit-cards/diners' . $ext ) . '" alt="Diners" width="32" ' . $style . ' />';
}
```

Rather than trying to keep up with what types of Stripe accounts & currencies accept which types of cards we should let users display the CC icons they want to display.

Originally from: https://woothemes.zendesk.com/agent/tickets/434817

**Comment by roykho** [comment]
There is already a filter for that https://github.com/woothemes/woocommerce-gateway-stripe/blob/master/includes/class-wc-gateway-stripe.php#L101

**Comment by BFTrick** [comment]
There's a filter (which I pointed out to the user) but many of these users don't have coding skills. :(

We should add a bit of UI to make it possible for those users to customize.

**Comment by roykho** [comment]
I am not sure if adding additional UI for edge case is worth maintaining as majority of the people will not need to change this. In addition, adding this UI will mean we need to add it to all our payment gateways.

I understand most people may not be code savvy, however if we put this in our documentation with steps to add the code, it should suffice. We simply can't add every possible UI option just based on people may not know how to add code. That's like saying we should add UI options for every filter we have for all our products.

On the other hand if however more than 50% of the people need to filter this out, than yes I would agree that this should be made a UI option.

cc @gedex your thoughts on this?

**Comment by gedex** [comment]
yeah, I agree that we need to consider this when the demand is high. For now, we could improve our documentation to mention the filter. I'll keep this open in case similar request is coming.

**Comment by BFTrick** [comment]
I'm fine with that. Let's see if other users have this issue. 

Can you update the docs with the filter? Or let the docs people know what to do?

**Comment by pmciano** [comment]
Along the same lines, if a user doesn't have **Enable Stripe Checkout** checked off, the credit card image still shows the Bitcoin icon, even though you can only enter Bitcoin information through [Stripe Checkout](https://stripe.com/blog/stripe-checkout):

![Checkout](https://www.evernote.com/l/AAKKA2p4rHlGkLl_vYtGQ0WDwwb4u8W8fZgB/image.png)

If the credit card images shown were easily customizable, the user would be able to remove the Bitcoin image when Stripe Checkout is disabled, since it is superfluous.

**Comment by roykho** [comment]
@pmciano in this case bitcoin icon should be removed if not supported.

**Comment by silicondales** [comment]
This cropped up in a mobile checkout here, whereby client wanted to remove diners and JCB logos (neither of which they recognized fwiw!!) as these flow onto two lines in a mobile checkout... I feel like this setting could be a useful, albeit low priority, addition.

What's more edge case: actually having one of those cards, or wanting to remove them from displaying in your checkout!

**Comment by roykho** [comment]
@silicondales - as you can see more than a year ago this issue was opened and yet to have anyone else needing to have this as a full on UI setting. Most likely a filter will suffice. In addition, in our next Stripe 4.0 update, you will have much better control over what is shown through the filter which we will document.

**Comment by silicondales** [comment]
yeah absolutely - I agree its super low priority. Docs don't exist (that I can see), so I wrote some https://silicondales.com/tutorials/woocommerce-tutorials/remove-obscure-payment-logos-icons-woocommerce-stripe-gateway/ - though even this would be beyond the novice dev in my opinion.
