### ISSUE TITLE
Order notes do not provide Stripe Transaction details from version 3.0.0

### ISSUE THREAD

**Issue by spraveenitpro** [woothemes/woocommerce-gateway-stripe#26]
###### This is how the order notes look like with the versions prior to 3.0.0:

![](http://cld.wthms.co/1czCa/4UgmfR4t+)

_Please note that the order notes include the Stripe transaction details_

###### This is how the order notes look like on the latest 3.0.2

![](http://cld.wthms.co/16ZJg/4rTNGgfC+)

_Please note that the Stripe transaction detail has been missed_

@tommyshellberg @slash1andy @stevetested @seanreloaded @BFTrick  @gedex 

[Report in .Org](https://wordpress.org/support/topic/order-notes-issue-no-stripe-notes-after-stripe-update#post-8572607)

**Comment by gedex** [comment]
Dupe of #18 and already fixed in `master`.
