### ISSUE TITLE
Remove SSL notice when in 'test mode'

### ISSUE THREAD

**Issue by JoelStickney** [woothemes/woocommerce-gateway-stripe#30]
"Stripe is enabled, but the force SSL option is disabled; your checkout may not be secure! Please enable SSL and ensure your server has a valid SSL certificate - Stripe will only work in test mode."

Either add a filter to optionally remove this notice, or don't display it when the plugin is already in test mode. Would be helpful with all the local dev setups to not see this all the time.

**Comment by WPprodigy** [comment]
Thought about removing the notice if test mode is enabled, but then we lose a pretty big target audience that needs to know that stripe won't work when they try to go live.

And a filter seems a bit overkill for the situation. So instead, I'm thinking maybe just a specific css class could do the trick. You can have a temp css rule or function that hides the message. The same process that you'd need to follow if using a filter.
