### ISSUE TITLE
Customer data not appearing on Stripe Dashboard

### ISSUE THREAD

**Issue by spraveenitpro** [woothemes/woocommerce-gateway-stripe#33]
#### Earlier customer data would appear on Stripe Dashboard after order completion like below at https://dashboard.stripe.com/test/customers :

![](http://cld.wthms.co/eJnr/4bHuJpjK+) 

Now they do not. 

Reported [here](https://wordpress.org/support/topic/stripe-customers-are-not-created?replies=1#post-8602811)

@tommyshellberg @slash1andy @stevetested @seanreloaded @BFTrick @dwainm @gedex

**Comment by BFTrick** [comment]
Hey Praveen - I'm not quite understanding the bug here. What's different now? Screenshot?

**Comment by dwainm** [comment]
@spraveenitpro could you replicate this on your test environment?

**Comment by spraveenitpro** [comment]
@BFTrick @dwainm the flow of customer data from WC to Stripe seems to work now, my bad..closing
