### ISSUE TITLE
Customer Description Field in Stripe Should Show Full Name

### ISSUE THREAD

**Issue by BFTrick** [woothemes/woocommerce-gateway-stripe#35]
When a brand new customer (can't use an existing customer or email) makes a purchase they'll show up with just the _first name_ in the `Description` field under the `Customers` menu in Stripe. We should change this to show the full name.

![_test__customer_cus_8fvdexjerwglso](https://cloud.githubusercontent.com/assets/1065372/16654531/9141ddf4-4456-11e6-8ba3-c660e3b6177a.jpg)

Ref: https://woothemes.zendesk.com/agent/tickets/436749

**Comment by danieldudzic** [comment]
Another ticket: https://woothemes.zendesk.com/agent/tickets/448063

**Comment by BFTrick** [comment]
👏
