### ISSUE TITLE
Potential issues with automatic retry of subscription payments

### ISSUE THREAD

**Issue by thenbrent** [woothemes/woocommerce-gateway-stripe#37]
#### What I expected

The Stripe customer/card tokens set on a subscription to be honoured when processing renewal payments.

#### What happened instead

The customer ID stored in user meta against the subscription's `customer_user` was used when the payment failed using the customer/card tokens set on the subscription.

#### Steps to reproduce the issue

1. Purchase or [manually create](https://docs.woothemes.com/document/subscriptions/add-or-modify-a-subscription/) a subscription with Stripe as the payment method
2. [Change the customer and card ID on the subscription](https://docs.woothemes.com/document/subscriptions/add-or-modify-a-subscription/#section-8) to invalid tokens (e.g. https://cloudup.com/cBsC0D_2Fmv)
3. [Process a renewal payment for the subscription](https://docs.woothemes.com/document/subscriptions/add-or-modify-a-subscription/#section-12)
4. Observe that the payment processed correctly

#### Background & Issues

SHA: fb1cdf41 introduced a basic retry system to `scheduled_subscription_payment()` which would fallback to use the Stripe customer token set in user meta if the payment fails, for any reason, using customer/card tokens set on the subscription.

This becomes an issue if the customer was expecting to be able to use certain cards for certain subscriptions. For example, a customer may use a company credit card for one subscription, while using a personal card for other purchases in the same store. Or one customer may [purchase a subscription for someone else](https://github.com/prospress/woocommerce-subscriptions-gifting) and use that person's credit card for the payments instead of their own (like you might do for your grandmother to save her having to mess with the tech). (These issues aren't entirely new, Stripe has defaulted to user meta for getting a customer ID for a long time, but only when there was no customer/card token set on the subscription, not whenever a payment fails for any reason).

Subscriptions is introducing its own retry system into v2.1 (for full details, see: https://github.com/Prospress/woocommerce-subscriptions/pull/1298). While that is quite a different approach and not quite as elegant as this one (as it has to be payment gateway agnostic), it's probably a sufficient substitute to the system introduced with SHA: fb1cdf41.

Because of these issues and the impeding alternative, I think this retry system should be removed from `scheduled_subscription_payment()`.

If you guys agree, let me know and I'll submit a PR. 😄 

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by mikejolley** [comment]
@thenbrent happy for a PR to remove this from the subs part, if the retry system is left in place for the rest of the gateway :)
