### ISSUE TITLE
Translate error codes

### ISSUE THREAD

**Issue by Ndrou** [woothemes/woocommerce-gateway-stripe#39]
#### What I expected

Error messages on failure of payment are returned in english. They should be translatable.

Below a defined list of error codes
```
invalid_number	The card number is not a valid credit card number.
invalid_expiry_month	The card's expiration month is invalid.
invalid_expiry_year	The card's expiration year is invalid.
invalid_cvc	The card's security code is invalid.
incorrect_number	The card number is incorrect.
expired_card	The card has expired.
incorrect_cvc	The card's security code is incorrect.
incorrect_zip	The card's zip code failed validation.
card_declined	The card was declined.
missing	There is no card on a customer that is being charged.
processing_error	An error occurred while processing the card.
```

https://stripe.com/docs/api#errors

**Comment by roykho** [comment]
Can you please give one example of an error ( full details ) so we know what context you're referring to?

**Comment by Ndrou** [comment]
Sorry for the approximate description, I updated the issue :)

**Comment by samuelaguilera** [comment]
Those error messages are returned by Stripe.com and unfortunately they don't provide support for other languages, just English.

But there's a workaround, create an array of possible returned card error codes and API error types with the appropriate error messages translated, then check the responseObject.response.error.type before returning the error message to the user.

The following is a customized version of onError function in assets/js/stripe.js that does the trick:

```
		onError: function( e, responseObject ) {

		    var errorMessagesTranslated = {
		    // Card error messages
		  	invalid_number: "The card number is not a valid credit card number.",
		  	invalid_expiry_month: "The card's expiration month is invalid.",
		  	invalid_expiry_year: "The card's expiration year is invalid.",
		  	invalid_cvc: "The card's security code is invalid.",
		  	incorrect_number: "The card number is incorrect.",
		  	expired_card: "The card has expired.",
		  	incorrect_cvc: "The card's security code is incorrect.",
		  	incorrect_zip: "The card's zip code failed validation.",
		  	card_declined: "The card was declined.",
		  	missing: "There is no card on a customer that is being charged.",
		  	processing_error: "An error occurred while processing the card.",
		 	// API error messages
		  	invalid_request_error: "Invalid request errors arise when your request has invalid parameters.",
		  	api_connection_error: "Failure to connect to Stripe's API",
		  	api_error: "API errors cover any other type of problem (e.g., a temporary problem with Stripe's servers) and are extremely uncommon.",
		  	authentication_error: "Failure to properly authenticate yourself in the request.",
		  	rate_limit_error: "Too many requests hit the API too quickly."
			};

			$( '.woocommerce-error, .stripe_token' ).remove();

			// To be able to return translated messages for card errors and API errors we need to perform some checking
		    if ( responseObject.response.error.type == 'card_error' ){
				$( '#stripe-card-number' ).closest( 'p' ).before( '<ul class="woocommerce_error woocommerce-error"><li>' + errorMessagesTranslated[ responseObject.response.error.code ] + '</li></ul>' );
		    } else if ( responseObject.response.error.type == 'invalid_request_error' || responseObject.response.error.type == 'api_connection_error' || responseObject.response.error.type == 'authentication_error' || responseObject.response.error.type == 'rate_limit_error') {
				$( '#stripe-card-number' ).closest( 'p' ).before( '<ul class="woocommerce_error woocommerce-error"><li>' + errorMessagesTranslated[ responseObject.response.error.type ] + '</li></ul>' );
		    } else { // Prevent undefined error if the error message is not covered by the above
		    	$( '#stripe-card-number' ).closest( 'p' ).before( '<ul class="woocommerce_error woocommerce-error"><li>' + responseObject.response.error.message + '</li></ul>' );
		    }

			wc_stripe_form.unblock();
		},
```
You can simply translate the messages for each error code/type in errorMessagesTranslated  to your language and replace the original function in stripe.js with this one.

Obviously this is just a dirty fix to allow you to have translated error messages in the meantime.

For a better approach errorMessagesTranslated should be removed from the above function and created using wp_localize_script() in class-wc-gateway-stripe.php allowing it to be translated using the .po file.

**Comment by erikmolenaarnl** [comment]
Hi,

I have tried to apply this (dirty!) fix and to change lines, but there is no effect. It seems the onError function in \woocommerce-gateway-stripe-master\assets\js is ignored completely, as even below code has no effect and still says "Your card was declined." when I place the plugin in test mode and try the special VISA number for a declined card return code: 4000000000000002:

`		onError: function( e, responseObject ) {
			$( '.woocommerce-error, .stripe_token' ).remove();
			$( '#stripe-card-number' ).closest( 'p' ).before( '<ul class="woocommerce_error woocommerce-error"><li>HELLO WORLD!</li></ul>' );
			wc_stripe_form.unblock();
		},`

You have any idea what is going on? Thanks for your help!

Kind regards
Erik

**Comment by hannahswain** [comment]
Someone else asking for this, who chose to go with a different plugin where it was possible: 
https://wordpress.org/support/topic/translate-the-error-messages/
