### ISSUE TITLE
Ensure we're enforcing TLS 1.2

### ISSUE THREAD

**Issue by mattyza** [woothemes/woocommerce-gateway-stripe#45]
https://github.com/stripe/stripe-php/pull/277

Lets see if there's a way we can enforce TLS 1.2, when using `wp_remote_post()`, as we do.

cc @mikejolley @gedex

**Comment by olivierbellone** [comment]
Hey! I'm one of the Stripe engineers that worked on the issue you mentioned.

I've skimmed through WP's source code and they don't seem to do anything in particular regarding TLS versions, in both their `curl` and `streams` transport layers:

- no reference to `CURLOPT_SSLVERSION` anywhere in https://developer.wordpress.org/reference/classes/wp_http_curl/

- no reference to `STREAM_CRYPTO` or `tls` anywhere in https://developer.wordpress.org/reference/classes/wp_http_streams/

So in both cases, the developers probably assumed that the crypto stack would do the sane thing and use the highest available protocol version.

Sadly, it seems that's not always the case in practice, and there are systems that are capable of using TLS 1.2 but won't use it by default. In Stripe's PHP bindings, we fixed this by checking the OpenSSL version ourselves, and manually forcing TLS 1.2 if it's supported (i.e. if OpenSSL is >= 1.0.1). It's not the most elegant solution but it seems to have done the trick for us.

In [this issue](https://core.trac.wordpress.org/ticket/34924) from 8 months ago, a WordPress dev said:
> We don't explicitly set any `CURLOPT_SSLVERSION` in core, so cURL should be able to make the determination itself based on the protocols available to it and those offered by the server. The `http_api_curl` filter can be used to set more explicit versions.

Something like this should work (completely untested):
```php
add_action('http_api_curl', function($curl)
{
    if (!$curl) {
        return;
    }

    if (OPENSSL_VERSION_NUMBER >= 0x1000100f) {
        if (!defined('CURL_SSLVERSION_TLSv1_2')) {
            // Note the value 6 comes from its position in the enum that
            // defines it in cURL's source code.
            define('CURL_SSLVERSION_TLSv1_2', 6); // constant not defined in PHP < 5.5
        }
        curl_setopt($curl, CURLOPT_SSLVERSION, CURL_SSLVERSION_TLSv1_2);
    } else {
        if (!defined('CURL_SSLVERSION_TLSv1')) {
            define('CURL_SSLVERSION_TLSv1', 1); // constant not defined in PHP < 5.5
        }
        curl_setopt($curl, CURLOPT_SSLVERSION, CURL_SSLVERSION_TLSv1);
    }
});
```

Anyway, just my 2 cents. I'm far from a PHP or Wordpress expert, so please take what I said with a grain of salt.

**Comment by mattyza** [comment]
Thank you, @olivierbellone.

We've enforced TLS 1.2 in a few of our other extensions for WooCommerce as well, so we'll most likely replicate that here.

cc @mikejolley

**Comment by olivierbellone** [comment]
Hey guys. Getting back to you since we're about to make a few changes related to TLS 1.2 in our own library.

It turns out that the advice I gave above is not ideal. The reason is that `OPENSSL_VERSION_NUMBER` returns the OpenSSL version that PHP itself is linked against. However, when using `curl_*` functions for outbound connections, PHP uses curl, which may itself be linked against a _different_ version of OpenSSL, or even use a different SSL library altogether (such as NSS on RedHat/CentOS systems, or SecureTransport on OS X systems).

Trying to set the appropriate `CURLOPT_SSLVERSION` option based on `OPENSSL_VERSION_NUMBER` has caused issues for some of our users. After looking at a lot of different systems and configurations, we've decided that the best course of action is to follow the advice from [PHP's documentation](https://secure.php.net/manual/en/function.curl-setopt.php):
> Your best bet is to not set this and let it use the default. 
and provide a way for our users to manually set `CURLOPT_SSLVERSION` themselves if they need to.

For more information, see the PR here: https://github.com/stripe/stripe-php/pull/299.

**Comment by roykho** [comment]
Hi @olivierbellone - awesome, thanks for reporting back. We'll implement with your advice.

**Comment by Rubious** [comment]
We're getting an error message because this plugin is still using TLS 1.0 - any idea how to fix this?

> Stripe no longer supports API requests made with TLS 1.0. Please initiate HTTPS connections with TLS 1.2 or later. You can learn more about this at https://stripe.com/blog/upgrading-tls.

I believe this is only happens on accounts created since July 1st.

**Comment by gedex** [comment]
@Rubious If you got that error message, most of the time it's caused by server configuration. Please contact your hosting support to enable TLS 1.2.

**Comment by Rubious** [comment]
@gedex No I've confirmed using Stripe's own check that the server is fine, it must be the plugin?

**Comment by gedex** [comment]
@Rubious Can you try this plugin https://wordpress.org/plugins/tls-1-2-compatibility-test/ and see if compat test passed? It's only [`wp_safe_remote_request`](https://github.com/woothemes/woocommerce-gateway-stripe/blob/master/includes/class-wc-stripe-api.php#L54) being used for API call.

**Comment by Rubious** [comment]
@gedex that says TLS 1.2 is not enabled, however https://support.stripe.com/questions/how-do-i-upgrade-my-stripe-integration-from-tls-1-0-to-tls-1-2#php says it is? I'm confused as to why the Stripe API works fine but the WooCommerce plugin does not.

**Comment by gedex** [comment]
@Rubious What cURL SSL Version you got from TLS compat plugin? Any notes worth mentioned? 

This might be related to https://core.trac.wordpress.org/ticket/34924. See the suggestion there or try @olivierbellone workaround in https://github.com/woothemes/woocommerce-gateway-stripe/issues/45#issuecomment-238919177.
