### ISSUE TITLE
Stripe returns white screen when CVC is wrong

### ISSUE THREAD

**Issue by ValeDeOro** [woothemes/woocommerce-gateway-stripe#50]
#### What I expected

If a customer by mistake enteres a wrong CVC, I expected to see an error message they can correct their mistake. 

#### What happened instead

Instead, the user gets a white screen. 

Fatal error: Uncaught exception 'Exception' with message 'Your card's security code is incorrect.' in /storage/content/81/151281/japanmysterybox.com/public_html/wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-gateway-stripe.php:544

#### Steps to reproduce the issue

On the the My Account page, select the Payment Methods tab.
Click "Add Payment Method"
Use the card number 4000000000000127 (following these testing card numbers: https://cloudup.com/c0EOTyt_3rM)

![](https://cloudup.com/cYQ_nbrwOKa+)
https://cloudup.com/cYQ_nbrwOKa

Use an expiry and CVC then click Add Card. 

Voilá, white screen. 

It seems to work when Stripe is in test mode, but doesn't work when live (tested by ProsPress)

459374-zd-woothemes

-------------------

- [x] Issue assigned to next milestone.
- [x] Issue assigned a priority (will be assessed by maintainers).

**Comment by ValeDeOro** [comment]
Additional information from the customer, after he talked to Stripe developers:

It looks like the WooCommerce Stripe plugin code does not correctly handle exceptions when adding cards to Customer objects. You can see the code below:

https://github.com/woothemes/woocommerce-gateway-stripe/blob/master/includes/legacy/class-wc-gateway-stripe.php#L544

You can see that the code is checking the return value of the `add_card` method, but is not catching exceptions thrown by the Stripe PHP bindings, which the method by which the bindings communicate errors.

Without catching exceptions, you'll see this "uncaught exception" error from PHP, and the application will fail to continue.

The particular code with this problem is treated as legacy code by WooCommerce.

The legacy code is loaded when the `WC_Payment_Gateway_CC` class cannot be found: 
https://github.com/woothemes/woocommerce-gateway-stripe/blob/7e70e76eb6761db2af65f00ccaaba25bde7b794a/woocommerce-gateway-stripe.php#L289

The class was added in 2.6.0: 
https://github.com/woothemes/woocommerce/blob/117990d95fd0536413d8b9204f6cddbdfb52132e/includes/gateways/class-wc-payment-gateway-cc.php#L9

**Comment by gedex** [comment]
@ValeDeOro that means store uses WC 2.6 but still on old version of WC Stripe.

**Comment by roykho** [comment]
According to @gedex this can be closed as customer just needs to update to the latest release.
