### ISSUE TITLE
JCB credit cards

### ISSUE THREAD

**Issue by craigdcraig** [woothemes/woocommerce-gateway-stripe#53]
#### What I expected

the woocommerce stripe gateway accepts JCB credit cards

#### What happened instead

when entering a JCB card, the stripe modal popup just blinks, gives no auth, no error, to denial message, no processing indicator. The gateway is sending nothing to Stripe...there is no record of the attempt on the Stripe site.

#### Steps to reproduce the issue

Using Stripe gateway 3.0.2.
woocommerce 2.6.4
WordPress 4.6
VISA and AmEx cards auth and capture with no problem. With the same setup and same processes for JCB I get no response from the woocommerce strip gateway.

All the documentation indicates JCB is accepted. Please help.

Thanks,
Craig

PLEASE NOTE
- These comments won't show up when you submit the issue.
- Everything is optional, but try to add as many details as possible.
- Screenshot worth a thousand words, use screenshots if possible.
- If requesting a new feature, explain why you'd like to see it added.
- Please apply appropriate labels on the issue
-->

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
I just tested this and I have no issues with JCB cards. Can you please test this with Stripe Checkout disabled?

**Comment by craigdcraig** [comment]
This was fixed a long time ago. Stripe gateway to woocommerce is now clearing JCB cards.
