### ISSUE TITLE
Partial payment isn't honored with Account Funds

### ISSUE THREAD

**Issue by hannahswain** [woothemes/woocommerce-gateway-stripe#57]
#### What I expected

When Partial Payments is enabled in the WooCommerce Account Funds plugin settings, I would expect only 4 GBP to be charged via Stripe as 32 GBP were paid for via Account Funds:

![2016-09-08_08-45-56](https://cloud.githubusercontent.com/assets/17844465/18339799/e00f6d76-75a1-11e6-99aa-2cc5596c838d.png)

#### What happened instead

The Account Funds were removed from the user's account, which is correct, but the full amount of 36 GBP was send to Stripe: 

The Stripe log says the following: 

`09-08-2016 @ 06:45:56 - Info: Begin processing payment for order 587 for the amount of 36`

Here's the Stripe dashboard:

![2016-09-08_08-58-12](https://cloud.githubusercontent.com/assets/17844465/18339897/6656ebb6-75a2-11e6-8b89-4eba015da87a.png)

#### Steps to reproduce the issue

1. Ensure that Partial Payment is enabled on the Account Funds setting
2. Ensure that the current user has funds on their account
3. Add products to the cart with a total value greater than the amount of funds on the account
4. Choose to pay part of the payment with account funds
5. Choose to pay the remainder with Stripe
6. Complete checkout

466156-zd-woothemes

**Comment by roykho** [comment]
Issue moved to [woothemes/woocommerce-account-funds #57](https://github.com/woothemes/woocommerce-account-funds/issues/57) via [**ZenHub**](https://www.zenhub.com/)

**Comment by andrewlreeve** [comment]
@roykho has this been fixed in woocommerce-account-funds? I don't have access to the repo but I'm facing the same issue with V2.0.15.

**Comment by roykho** [comment]
@andrewlreeve - it has not but will be by the next release.

**Comment by andrewlreeve** [comment]
@roykho do you have an estimated release date for a patched version? It's a breaking bug so wondering if it's likely to be in the next week, or more likely in the next month and we need to get our own dev to look at it.
