### ISSUE TITLE
Any Reason for two XHR Requests to https://api.stripe.com/v1/tokens

### ISSUE THREAD

**Issue by quasel** [woothemes/woocommerce-gateway-stripe#61]
#### What I expected

If i submit the Form the card get checked once with https://api.stripe.com/v1/tokens
https://api.stripe.com/v1/token

#### What happened instead

the request to https://api.stripe.com/v1/tokens is done twice 

#### Possible reason 
onSubmit is fired twice  -> https://github.com/woothemes/woocommerce-gateway-stripe/blob/master/assets/js/stripe.js#L28

once for submit 
and once for checkout_place_order_stripe because of https://github.com/woothemes/woocommerce/blob/f4a30e3be630caad8c8c0392885a136ed4fd9f67/assets/js/frontend/checkout.js#L349

is this done on purpose or a bug? 

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by quasel** [comment]
fixed with #67

**Comment by roykho** [comment]
Ok so my test was before token was checked again on this line https://github.com/woothemes/woocommerce-gateway-stripe/blob/master/assets/js/stripe.js#L73 

That gave me false positives with the `one` implementation as it did indeed reduce the event being fired but not the one we want. My assumption currently is that WC "perhaps" re-generates the form on AJAX thus re-binding the event again and thus making any other logic moot such as `off`. This is just an assumption but will investigate more.

**Comment by quasel** [comment]
the reason it's fired twice comes is noted in my first post - but guess i'll take a look at how other gateways handle it :P - or why we need to watch on both events ^^

**Comment by roykho** [comment]
Actually in my test it is fired more than 4 times and using `one` solves the issue of cutting it in half which now fires once per event type as stated in the `one` documentation. However I have since removed that as that doesn't solve your original issue which I originally thought was the culprit. For example if you removed "submit" as one of the events, you will see it is still firing twice.

**Comment by quasel** [comment]
Thats intresting in my setup with storefront it's only fired twice - with and without the multi step checkout but had to tweak a check to pass the first submit of the multi step checkout ^^

**Comment by roykho** [comment]
Does `onsubmit` fire only twice for you? Or just the XHR call to Stripe?

**Comment by quasel** [comment]
if i remeber correctly from my js debugging for reporting the issue it was one XHR from `submit` one from `checkout_place_order_stripe`
