### ISSUE TITLE
Gateway not works in regular mode (not stripe checkout)

### ISSUE THREAD

**Issue by studio404pl** [woothemes/woocommerce-gateway-stripe#64]
#### What I expected

proceed to checkout without errors, for now stripe token is missing

#### What happened instead

default checkout submit is initiated before stripe actually retrieve proper token. Token is populated into form AFTER checkout submit request. There's no hook to prevent submission on entire checkout form. I made breakdown in js for myself. Checkout submit not contains stripe token, it's added after getting back errors (they are caused with missing stripe token).

Everything work well with stripe checkout enabled but i want to handle it with regular cc fields.

#### Steps to reproduce the issue

Plugin version: 3.0.2
Woocommerce version: 2.6.4
WP version: 4.6.1

all is up to date, no other plugins that affect on submit process.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
I am not sure I understand what you mean? Are you saying no tokens are generated when you submit the form and therefore checkout doesn't process?

I am able to process the checkout form without any issues.

**Comment by studio404pl** [comment]
> I am not sure I understand what you mean? Are you saying no tokens are generated when you submit the form and therefore checkout doesn't process?

exactly, i see in console that main checkout form is submitted before token is generated at all.. so i am getting error that i should fill out cc details before proceed. after submitting form token is generated (i see that in console) but meantime it's cleared out again because gateway list is automatically refreshed by woocommerce.

**Comment by studio404pl** [comment]
@roykho - i can give you address for staging area to reproduce problem but i can't put that as public message.

**Comment by roykho** [comment]
Do you have custom code that manipulates the CC fields? Also please try switching to 2016 theme and re-test.

**Comment by studio404pl** [comment]
> Do you have custom code that manipulates the CC fields?

no, i don't. It works without any issue with paypal pro gateway with same cc fields.

> Also please try switching to 2016 theme and re-test.

It works with twenty sixteen theme but it's not a solution to my problem. I can reproduce bug, i don't see anything in console or logs.. so that issue is not cached at all.

**Comment by roykho** [comment]
So the issue then is not from our plugin but your theme. I would suggest you contact your theme author to fix. I have tried this on several themes 2016, Storefront, Canvas and they all work.

**Comment by avishai** [comment]
I just opened an issue that might be related: https://github.com/woocommerce/woocommerce-gateway-stripe/issues/170. The token doesn't get generated if the payment fields aren't exactly where WooCommerce puts them by default...
