### ISSUE TITLE
Declare Live Secret Key as a Secure Field

### ISSUE THREAD

**Issue by cellar-door** [woothemes/woocommerce-gateway-stripe#65]
I've submitted a patch for WooCommerce Core that would allow for plugins to declare settings fields as secure: https://github.com/woothemes/woocommerce/issues/11946 . This allows other plugins to then secure the keys prior to storage.

To enable this, we simply put a `'secure' => true,` into the field array. Then when getting the settings in the construct, we run through the fields, look for a secure field and then apply the filter as needed. Also in the API we put in a filter on the live_secure_key get_option so it can work as expected.

The pull request will come right after this. I've got a few discussion points on the specifics of the code that I can discuss on it.

**Comment by roykho** [comment]
Ref https://github.com/woothemes/woocommerce-gateway-stripe/pull/66
