### ISSUE TITLE
Add an option ot prevent users from adding cards in account/payment-methods outside of checkout

### ISSUE THREAD

**Issue by quasel** [woothemes/woocommerce-gateway-stripe#69]
Because the created card outside of the normal checkout does not add the address in the stripe request - reducing fraud detection e.g.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
I believe this should be addressed in WC core. Credit card billing fields should be optionally shown when adding payment method. Although not all payment gateways will support fraud checking in this manner. So perhaps it falls under custom as well.
